import { useState } from 'react';
import { exportPatch, downloadPatchFile, downloadPatchBlob } from '../utils/api';

/**
 * Export Patch modal with download functionality and
 * client-side JSON fallback.
 */
export default function ExportModal({ onClose, selectedLayers, steeringStrength, analysisResult }) {
    const [name, setName] = useState('');
    const [description, setDescription] = useState('');
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);
    const [error, setError] = useState(null);
    const [downloadStatus, setDownloadStatus] = useState(null);

    // Build the patch data locally as LAST RESORT fallback only
    const buildLocalPatch = (patchId) => ({
        patch_id: patchId || `local_${Date.now()}`,
        name: name,
        description,
        model: 'current',
        created_at: new Date().toISOString(),
        interventions: selectedLayers.map((layer) => ({
            layer,
            strength: steeringStrength,
            type: 'direction',
            direction_vector: null, // server export auto-computes via CAA
            notes: 'Auto-generated by SteerOps',
        })),
        analysis_summary: analysisResult?.interpretation?.summary || null,
    });

    const handleExport = async () => {
        if (!name.trim()) return;
        setLoading(true);
        setError(null);
        try {
            const res = await exportPatch({
                patch_name: name,
                description,
                interventions: selectedLayers.map((layer) => ({
                    layer,
                    strength: steeringStrength,
                    notes: `Auto-generated by SteerOps`,
                })),
                validation_data: {},
            });
            setResult(res);
        } catch (e) {
            setError(e.message);
        } finally {
            setLoading(false);
        }
    };

    // Always try server export first (computes direction vectors via CAA),
    // then download the server-produced patch file
    const handleDownload = async () => {
        setDownloadStatus('downloading');
        try {
            // Try server-side download first
            if (result?.patch_id) {
                downloadPatchFile(result.patch_id);
                setDownloadStatus('success');
                return;
            }
        } catch { }

        // Client-side fallback — always works but direction_vector will be null
        try {
            const patchData = result?.patch || buildLocalPatch(result?.patch_id);
            const filename = `steerops_${name.replace(/\s+/g, '_').toLowerCase()}.json`;
            downloadPatchBlob(patchData, filename);
            setDownloadStatus('success');
        } catch (e) {
            setDownloadStatus('error');
        }
    };

    // Direct download: export through server first (for direction vectors), then download
    const handleDirectDownload = async () => {
        if (!name.trim()) return;
        setDownloadStatus('downloading');
        setError(null);
        try {
            // Export via server to get direction vectors computed
            // This can take ~60s per layer (CAA auto-compute)
            const res = await exportPatch({
                patch_name: name || 'patch',
                description,
                interventions: selectedLayers.map((layer) => ({
                    layer,
                    strength: steeringStrength,
                    notes: `Auto-generated by SteerOps`,
                })),
                validation_data: {},
            });
            // Download the server-enriched patch
            const patchData = res?.patch || buildLocalPatch(res?.patch_id);
            const filename = `steerops_${(name || 'patch').replace(/\s+/g, '_').toLowerCase()}.json`;
            downloadPatchBlob(patchData, filename);
            setResult(res);
            setDownloadStatus('success');
        } catch (e) {
            console.error('Export failed, using local fallback:', e);
            setError(`Server export failed: ${e.message}. Using local fallback (direction vectors will be null).`);
            // Fallback: client-side patch without direction vectors
            const patchData = buildLocalPatch();
            const filename = `steerops_${(name || 'patch').replace(/\s+/g, '_').toLowerCase()}.json`;
            downloadPatchBlob(patchData, filename);
            setDownloadStatus('success');
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-fade-in"
            onClick={(e) => e.target === e.currentTarget && onClose()}>
            <div className="w-full max-w-md glass rounded-xl p-6 space-y-4 animate-slide-in">
                <div className="flex justify-between items-center">
                    <h3 className="text-sm font-semibold">Export Patch</h3>
                    <button onClick={onClose} className="text-text-tertiary hover:text-text-primary text-lg transition">×</button>
                </div>

                {!result ? (
                    <>
                        <div className="space-y-3">
                            <input
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                placeholder="Patch name…"
                                className="w-full px-3 py-2 rounded-lg bg-bg-primary border border-border-subtle
                  text-sm focus:outline-none focus:border-accent-green/50 transition"
                            />
                            <textarea
                                value={description}
                                onChange={(e) => setDescription(e.target.value)}
                                placeholder="Description (what behavior does this patch change?)…"
                                rows={2}
                                className="w-full px-3 py-2 rounded-lg bg-bg-primary border border-border-subtle
                  text-sm resize-none focus:outline-none focus:border-accent-green/50 transition"
                            />
                            <div className="p-3 rounded-lg bg-bg-primary border border-border-subtle text-xs space-y-1">
                                <div className="flex justify-between">
                                    <span className="text-text-tertiary">Layers</span>
                                    <span className="font-mono">{selectedLayers.map(l => `L${l}`).join(', ')}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-text-tertiary">Strength</span>
                                    <span className={`font-mono ${steeringStrength > 0 ? 'text-accent-green' : steeringStrength < 0 ? 'text-accent-red' : 'text-text-tertiary'}`}>
                                        {steeringStrength > 0 ? '+' : ''}{steeringStrength}
                                    </span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-text-tertiary">Interventions</span>
                                    <span className="font-mono">{selectedLayers.length}</span>
                                </div>
                            </div>
                        </div>

                        {error && (
                            <p className="text-xs text-accent-red p-2 rounded-lg bg-accent-red/10 border border-accent-red/20">
                                {error}
                            </p>
                        )}

                        <button
                            onClick={handleDirectDownload}
                            disabled={!name.trim() || downloadStatus === 'downloading'}
                            className="w-full py-2.5 rounded-lg font-medium text-sm bg-accent-green text-white
                hover:bg-accent-green-hover transition disabled:opacity-40 disabled:cursor-not-allowed"
                        >
                            {downloadStatus === 'downloading' ? 'Computing vectors… (may take a few minutes)'
                                : downloadStatus === 'success' ? 'Downloaded!'
                                    : 'Export Patch'}
                        </button>
                    </>
                ) : (
                    <div className="space-y-3 text-center">
                        <div className="text-4xl text-accent-green">✔</div>
                        <p className="text-sm font-medium">Patch exported successfully!</p>
                        <div className="p-3 rounded-lg bg-bg-primary border border-border-subtle text-xs text-left space-y-1">
                            <div className="flex justify-between">
                                <span className="text-text-tertiary">Patch ID</span>
                                <span className="font-mono text-accent-green">{result.patch_id?.slice(0, 8)}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-text-tertiary">Size</span>
                                <span className="font-mono">{result.file_size_kb} KB</span>
                            </div>
                        </div>

                        {/* Download Button */}
                        <button
                            onClick={handleDownload}
                            className={`w-full py-2.5 rounded-lg font-medium text-sm transition-all
                border ${downloadStatus === 'success'
                                    ? 'bg-accent-green/20 border-accent-green/50 text-accent-green'
                                    : 'bg-gradient-to-r from-accent-blue/20 to-accent-purple/20 border-accent-blue/30 hover:border-accent-blue/60 hover:shadow-lg hover:shadow-accent-blue/10'
                                }`}
                        >
                            {downloadStatus === 'downloading' ? 'Downloading…'
                                : downloadStatus === 'success' ? 'Downloaded!'
                                    : 'Download JSON'}
                        </button>

                        <button
                            onClick={onClose}
                            className="w-full py-2 rounded-lg text-sm border border-border-subtle hover:border-border-hover transition"
                        >
                            Close
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
}
